### ISSUE TITLE
existence of globalThis

### ISSUE THREAD

**Issue by frank-dspeed** [wintercg/proposal-common-minimum-api#12]
The existence of globalThis is agreed on by the spec and it should exist in all environments as it is a reaction to the following problem:

- global variable name can not clear be detected while it always exists by the standard there is no single ecmascript compatible environment possible without a global scope no matter which name it is assigned to. 

## why
it got questioned and i want to give my 5cent as representant of 4 engines and 2 languages where it is the case that it always exists 
- https://github.com/wintercg/admin/pull/21/commits/fee59f2c7642ad17c8f58b6fc19aee166bfae622
- see: https://github.com/tc39/proposal-global from @wintercg member @ljharb also @tc39 member

**Comment by lucacasonato** [comment]
This is not something we have to call out explicitly, as the existence of `globalThis` is already something that all conformant ECMA262 implementations need to have.

**Comment by frank-dspeed** [comment]
@lucacasonato then i missreaded the notes in the last meeting how should i interpret that ? It reads for me like it is qestioned if we should assume the existince of globalThis
