### ISSUE TITLE
Blob and File

### ISSUE THREAD

**Issue by jasnell** [wintercg/proposal-common-minimum-api#17]
Node.js, Deno, and Cloudflare Workers all provide implementations of `Blob`. 

Deno and Workers provide implementations of `File`.

These should likely be included in the minimum common api.

**Comment by legendecas** [comment]
How is Deno and Cloudflare workers' implementation of `File` going to interoperate with platform APIs? AFAICT, Deno's file operations are based on [`Deno.FsFile`](https://doc.deno.land/deno/stable/~/Deno.FsFile), which is not a `File` interface. I didn't find any manuals on the Cloudflare Workers website about `File`.

On the web platform, the `File` interface is primarily used with the `<input>` element and the HTML drag and drop API. Both of which I failed to see the use cases on the Deno and CF workers.

Would you mind elaborating on the `File` implementation and its platform integration?

**Comment by Tseian** [comment]
In Bytedance, Hourai.js support `File` and `Blob` according to [W3C File API spec](https://www.w3.org/TR/FileAPI/).
`File` is a `Blob` which has a special `Symbol.toStringTag` name "File" and some other properties.

**Comment by legendecas** [comment]
@Tseian that's great to know. Would you mind sharing how the `File` interface is integrated into your platform? As I said above, I didn't find there are signals that the very limited `File` interface is being used in the wild other than in browsers. It would be great to know how _common_ the usage is of the API in the server-side runtimes.

**Comment by Tseian** [comment]
> @Tseian that's great to know. Would you mind sharing how the `File` interface is integrated into your platform? As I said above, I didn't find there are signals that the very limited `File` interface is being used in the wild other than in browsers. It would be great to know how _common_ the usage is of the API in the server-side runtimes.

We use `File` in `Fetch API` to make `Fetch API` can upload  data to remote server as a`File` or download `File` data from remote server. Maybe there are some other usage we have not found.

**Comment by legendecas** [comment]
@Tseian thank you for your sharing. IIUC, we can receive a `Blob` from `Response` in `fetch` or send blobs as the body with `Request`. I may miss a point here, but, how do you create a `File` from a `Response`, is that an extension that is not part of the fetch spec in your implementation? For a generic HTTP request and response, I may not see how to construct a `File` with the necessary part like file name, type, and lastModified.

**Comment by Tseian** [comment]
@legendecas I just read some implementation code. I have made a mistake, the `File` just is used in [`FormData`](https://xhr.spec.whatwg.org/#dom-formdata-append) for uploading data to remote server. There is no extension. Yes, after some thoughts, I agree with you on "I may not see how to construct a File with the necessary part like file name, type, and lastModified.". Name, type and lastModified really look like no sense.

**Comment by lucacasonato** [comment]
> AFAICT, Deno's file operations are based on [Deno.FsFile](https://doc.deno.land/deno/stable/~/Deno.FsFile), which is not a File interface.

No, our `File` global is not the same as `Deno.FsFile`, but rather the web standard `File`. We used to have a `Deno.File`, but deprecated this due to the naming confusion (it is now `Deno.FsFile`).

**Comment by sashafirsov** [comment]
The [W3C File API spec](https://www.w3.org/TR/FileAPI/) File concept as a Blob operations does not fit into limitations of embedded environments where RAM is limited resource. 

Rather embedded environments would gain on file API for `random access`, `streaming`, `pipeline processing`, `memory mapping`. All currently supported by most of OS, some embedded. I have not seen proposals on such essential needs in the W3C community groups yet, anyone dare to penetrate this gap?

Disclaimer: the streaming and pipeline exist but not tied to W3C File. [Node.js fs streaming](https://www.digitalocean.com/community/tutorials/how-to-work-with-files-using-streams-in-node-js) does not count.

**Comment by Ethan-Arrowood** [comment]
File is landing in Node 19: https://github.com/nodejs/node/pull/45139
