### ISSUE TITLE
Use cases for AbortSignal.any()

### ISSUE THREAD

**Issue by jasnell** [wintercg/proposal-common-minimum-api#25]
One of the active discussions at the whatwg/dom repo is creation of an AbortSignal that can follow other AbortSignals... see https://github.com/whatwg/dom/issues/920

There is a proposal on the table for `AbortSignal.any()` here: https://github.com/shaseley/abort-signal-any/blob/main/README.md

The key question for this group is whether the proposal looks good and whether wintercg has any feedback for the discussion.

**Comment by jasnell** [comment]
There's no further action to be done here. `AbortSignal.any(...)` was added to the spec.

**Comment by mk-pmb** [comment]
Cancelling an AbortSignal sounds interesting. We should then also add a way to re-engage it later. We could use this to enforce timeouts for tasks on low-priority queues only when there are tasks in a higher-priority queue.
