### ISSUE TITLE
Expected `fetch` to be in the common minimum API

### ISSUE THREAD

**Issue by timfish** [wintercg/proposal-common-minimum-api#27]
Already exists in at least Cloudflare Workers, Deno and Node.js...

**Comment by benjamingr** [comment]
Sure, see https://github.com/wintercg/fetch/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by timfish** [comment]
Oh it even has it's own repository. 

Should it not also be listed under `globalThis` [here](https://github.com/wintercg/proposal-common-minimum-api/blob/bdd56a3bb8cdc95ac76633199c79298815d5e4ca/index.bs#L74)?

**Comment by sashafirsov** [comment]
`fetch` is just one of API for data retrieval. How valuable would be other venues for common minimum API?
* [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) 
* [Streams](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API)  

Following kind of questions could help with value matrix:
* if I am a device vendor, would be `stream` preferable over blob-in-memory by `fetch()`?
* -||-, would be socket 2-way connection be preferable to pulling?

**Comment by andreubotella** [comment]
If `fetch` is added to the common minimum API, the [WebAssembly Web API](https://webassembly.github.io/spec/web-api/), which defines `WebAssembly.instantiateStreaming` and `WebAssembly.compileStreaming`, should be added as well. It can't be added currently because it relies on the `Response` interface.

**Comment by andreubotella** [comment]
`fetch` and the wasm Web API are now added.
