### ISSUE TITLE
request: WebAssembly, Worker, MessageChannel, postMessage, SharedArrayBuffer, Atomics

### ISSUE THREAD

**Issue by trusktr** [wintercg/proposal-common-minimum-api#44]
These seem like great things to add.

And just to start the conversation, additionally it would be amazing to spec Winter APIs out for WebAssembly, not just for JS, as a (web-friendly) alternative to WASI. It would be useful for compiling to native as well.

**Comment by ljharb** [comment]
SharedArrayBuffer and Atomics are part of JavaScript and can't ever be absent.

**Comment by jasnell** [comment]
`Worker` is not really implemented consistently across the runtimes so I'm not sure that's something we can claim as a "common minimum" just yet. `MessageChannel` and `postMessage` is something I think would qualify, however.

**Comment by Qard** [comment]
MessageChannel behaviour is kind of dependent on whatever Worker it would connect to though, is it not?

**Comment by jasnell** [comment]
On this, we already include `WebAssembly` in the common minimum. There really isn't enough consistency with across runtimes with the `Worker`, `MessageChannel`, and `postMessage` APIs yet to include those in a common minimum, and the `SharedArrayBuffer` and `Atomics` are already language level so do not need to be covered here. Given that, I'm going to close this.
