### ISSUE TITLE
https://common-min-api.proposal.wintercg.org/: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by guest271314** [wintercg/proposal-common-minimum-api#48]
![Screenshot_2023-07-23_14-35-02](https://github.com/wintercg/proposal-common-minimum-api/assets/4174848/9f08a066-39c9-48c0-9323-cb88a8821c00)

**Comment by ljharb** [comment]
Loads fine for me; seems like it's an issue on your end.

**Comment by voxpelli** [comment]
It was reported in the Matrix chat as well, that the site was appearing flaky

**Comment by guest271314** [comment]
Loads on Firefox, not Chromium. Interesting. Changed DNS to Google public DNS then back to default provider, now loading on Chromium.
